#h2
spring.datasource.url.h2=jdbc:h2:mem:blogs;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username.h2=sa
spring.datasource.password.h2=

##postgres
spring.datasource.url.postgres=jdbc:postgresql://localhost:5433/blog
spring.datasource.username.postgres=admin
spring.datasource.password.postgres=admin